### ISSUE TITLE
Credential recovery fails on unicode decoding

### ISSUE THREAD

**Issue by acepace** [emtunc/SlackPirate#1]
Hey, 
Running on Python 3.6 on Windows, I get the following stack trace

START: Attempting to find references to credentials
Traceback (most recent call last):
  File "SlackPirate.py", line 454, in <module>
    find_credentials()
  File "SlackPirate.py", line 274, in find_credentials
    file_cleanup(file_credentials)
  File "SlackPirate.py", line 434, in file_cleanup
    lines = set(file.readlines())
  File "C:\Program Files\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3702: character maps to <undefined>

This happens consistently

**Comment by emtunc** [comment]
@acepace Fixed! (I think) - I accidentally left out the `encoding` option in the file_cleanup function. Give it a try and let me know how well it works now?

#06dfe58
