### ISSUE TITLE
is_rate_limited needs improving as it can occasionally error out

### ISSUE THREAD

**Issue by emtunc** [emtunc/SlackPirate#21]
```
START: Attempting to find references to interesting URLs
INFO: Slack API rate limit hit - sleeping for 60 seconds
Traceback (most recent call last):
  File "SlackPirate.py", line 643, in <module>
    scan(token=provided_token, output_info=collected_output_info)
  File "SlackPirate.py", line 463, in find_interesting_links
    pagination[query] = (r['messages']['pagination']['page_count'])
KeyError: 'messages'
```

The above happens because it first does a HTTP request which returns 'ratelimited' as the response... the script then sleeps for 60 seconds THEN continues to look for something on the page which it can't because it's still holding the contents of the 'ratelimited' page.

**Comment by emtunc** [comment]
Improved as part of #24
