### ISSUE TITLE
Error: Crashes when downloading files

### ISSUE THREAD

**Issue by ghost** [emtunc/SlackPirate#39]
Traceback (most recent call last):
  File "./SlackPirate.py", line 831, in <module>
    scan(token=provided_token, scan_context=collected_scan_context)
  File "./SlackPirate.py", line 680, in download_interesting_files
    _retrieve_file_batch(batch, completed_file_names)
  File "./SlackPirate.py", line 601, in _retrieve_file_batch
    request.start()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by Phil-ThePower-Pearce** [comment]
I've also been getting many open files error

**Comment by emtunc** [comment]
> I've also been getting many open files error

Hey @Phil-ThePower-Pearce what version of the tool were you using? Also which OS were you running it from?
