### ISSUE TITLE
unable to get any data

### ISSUE THREAD

**Issue by random-robbie** [emtunc/SlackPirate#60]
Unable to get data.

this was using a token.

Python 3.7.2

```
[Credentials]: Attempting to find references to credentials
Traceback (most recent call last):
  File "./SlackPirate.py", line 1006, in <module>
    _interactive_command_line(args, selected_agent)
  File "./SlackPirate.py", line 937, in _interactive_command_line
    scan(token=provided_token, scan_context=collected_scan_context)
  File "./SlackPirate.py", line 393, in find_credentials
    page_count_by_query[query] = (r['messages']['pagination']['page_count'])
KeyError: 'messages'
```

**Comment by random-robbie** [comment]
Looks like the return from the token for 

```
/api/users.list
```

```
{
    "ok": false,
    "error": "invalid_auth"
}
```

**Comment by random-robbie** [comment]
Looks like this should be a POST request.

**Comment by random-robbie** [comment]
Error handling needed for `/api/users.info`

```
{
    "ok": false,
    "error": "invalid_auth"
}
```

**Comment by emtunc** [comment]
Most/all of these problems should be resolved now thanks to @MayerDaniel 's PR: https://github.com/emtunc/SlackPirate/pull/63
